SPOTIFY_OBJECT_SPECS = (
    {
        "name": "Paging",
        "base": "Page",
    },
    {
        "name": "Cursor",
        "properties": (
            {"field": "after"},
            {"field": "before"},
        ),
    },
    {
        "name": "CursorPaging",
        "base": "Page",
        "properties": (
            {"field": "cursors", "kind": "object", "class": "Cursor"},
        ),
    },
    {
        "name": "ExternalUrl",
        "properties": (
            {"field": "spotify"},
        ),
    },
    {
        "name": "ExternalId",
        "properties": (
            {"field": "isrc"},
            {"field": "ean"},
            {"field": "upc"},
        ),
    },
    {
        "name": "Restriction",
        "properties": (
            {"field": "reason"},
        ),
    },
    {
        "name": "Followers",
        "properties": (
            {"field": "href"},
            {"field": "total"},
        ),
    },
    {
        "name": "Image",
        "properties": (
            {"field": "url"},
            {"field": "height"},
            {"field": "width"},
        ),
    },
    {
        "name": "Copyright",
        "properties": (
            {"field": "text"},
            {"field": "type"},
        ),
    },
    {
        "name": "ExplicitContentSettings",
        "properties": (
            {"field": "filter_enabled"},
            {"field": "filter_locked"},
        ),
    },
    {
        "name": "User",
        "properties": (
            {"field": "display_name"},
            {"field": "href"},
            {"field": "id"},
            {"field": "type"},
            {"field": "uri"},
            {"field": "external_urls", "kind": "object", "class": "ExternalUrl"},
            {"field": "followers", "kind": "object", "class": "Followers"},
            {"field": "images", "kind": "objects", "class": "Image"},
        ),
    },
    {
        "name": "PrivateUser",
        "properties": (
            {"field": "account_id"},
            {"field": "country"},
            {"field": "display_name"},
            {"field": "email"},
            {"field": "href"},
            {"field": "id"},
            {"field": "product"},
            {"field": "type"},
            {"field": "uri"},
            {"field": "explicit_content", "kind": "object", "class": "ExplicitContentSettings"},
            {"field": "external_urls", "kind": "object", "class": "ExternalUrl"},
            {"field": "followers", "kind": "object", "class": "Followers"},
            {"field": "images", "kind": "objects", "class": "Image"},
        ),
    },
    {
        "name": "PlaylistItemsRef",
        "properties": (
            {"field": "href"},
            {"field": "total"},
        ),
    },
    {
        "name": "AlbumsRef",
        "properties": (
            {"field": "href"},
            {"field": "total"},
        ),
    },
    {
        "name": "SnapshotResult",
        "properties": (
            {"field": "snapshot_id"},
        ),
    },
    {
        "name": "TrackPage",
        "base": "Paging",
        "item_class": "Track",
    },
    {
        "name": "AlbumPage",
        "base": "Paging",
        "item_class": "Album",
    },
    {
        "name": "ArtistPage",
        "base": "Paging",
        "item_class": "Artist",
    },
    {
        "name": "PlaylistPage",
        "base": "Paging",
        "item_class": "Playlist",
    },
    {
        "name": "CategoryPage",
        "base": "Paging",
        "item_class": "Category",
    },
    {
        "name": "PlaylistTrackPage",
        "base": "Paging",
        "item_class": "PlaylistTrack",
    },
    {
        "name": "EpisodePage",
        "base": "Paging",
        "item_class": "Episode",
    },
    {
        "name": "ShowPage",
        "base": "Paging",
        "item_class": "Show",
    },
    {
        "name": "AudiobookPage",
        "base": "Paging",
        "item_class": "Audiobook",
    },
    {
        "name": "ChapterPage",
        "base": "Paging",
        "item_class": "Chapter",
    },
    {
        "name": "SavedAlbumPage",
        "base": "Paging",
        "item_class": "SavedAlbum",
    },
    {
        "name": "SavedTrackPage",
        "base": "Paging",
        "item_class": "SavedTrack",
    },
    {
        "name": "SavedEpisodePage",
        "base": "Paging",
        "item_class": "SavedEpisode",
    },
    {
        "name": "SavedShowPage",
        "base": "Paging",
        "item_class": "SavedShow",
    },
    {
        "name": "CursorPage",
        "base": "CursorPaging",
    },
    {
        "name": "ArtistCursorPage",
        "base": "CursorPaging",
        "item_class": "Artist",
    },
    {
        "name": "PlayHistoryCursorPage",
        "base": "CursorPaging",
        "item_class": "PlayHistory",
    },
    {
        "name": "ResumePoint",
        "properties": (
            {"field": "fully_played"},
            {"field": "resume_position_ms"},
        ),
    },
    {
        "name": "Author",
        "properties": (
            {"field": "name"},
        ),
    },
    {
        "name": "Narrator",
        "properties": (
            {"field": "name"},
        ),
    },
    {
        "name": "Error",
        "properties": (
            {"field": "status"},
            {"field": "message"},
        ),
    },
    {
        "name": "Context",
        "properties": (
            {"field": "type"},
            {"field": "href"},
            {"field": "uri"},
            {"field": "external_urls", "kind": "object", "class": "ExternalUrl"},
        ),
    },
    {
        "name": "Device",
        "properties": (
            {"field": "id"},
            {"field": "is_active"},
            {"field": "is_private_session"},
            {"field": "is_restricted"},
            {"field": "name"},
            {"field": "type"},
            {"field": "volume_percent"},
            {"field": "supports_volume"},
        ),
    },
    {
        "name": "Disallows",
        "properties": (
            {"field": "interrupting_playback"},
            {"field": "pausing"},
            {"field": "resuming"},
            {"field": "seeking"},
            {"field": "skipping_next"},
            {"field": "skipping_prev"},
            {"field": "toggling_repeat_context"},
            {"field": "toggling_shuffle"},
            {"field": "toggling_repeat_track"},
            {"field": "transferring_playback"},
        ),
    },
    {
        "name": "LinkedTrack",
        "properties": (
            {"field": "id"},
            {"field": "uri"},
            {"field": "href"},
            {"field": "type"},
            {"field": "external_urls", "kind": "object", "class": "ExternalUrl"},
        ),
    },
    {
        "name": "Category",
        "properties": (
            {"field": "href"},
            {"field": "id"},
            {"field": "name"},
            {"field": "icons", "kind": "objects", "class": "Image"},
        ),
    },
    {
        "name": "FeaturedPlaylists",
        "properties": (
            {"field": "message"},
            {"field": "playlists", "kind": "object", "class": "PlaylistPage"},
        ),
    },
    {
        "name": "SearchResults",
        "properties": (
            {"field": "tracks", "kind": "object", "class": "TrackPage"},
            {"field": "artists", "kind": "object", "class": "ArtistPage"},
            {"field": "albums", "kind": "object", "class": "AlbumPage"},
            {"field": "playlists", "kind": "object", "class": "PlaylistPage"},
            {"field": "shows", "kind": "object", "class": "ShowPage"},
            {"field": "episodes", "kind": "object", "class": "EpisodePage"},
            {"field": "audiobooks", "kind": "object", "class": "AudiobookPage"},
        ),
    },
    {
        "name": "TimeInterval",
        "properties": (
            {"field": "start"},
            {"field": "duration"},
            {"field": "confidence"},
        ),
    },
    {
        "name": "Section",
        "properties": (
            {"field": "start"},
            {"field": "duration"},
            {"field": "confidence"},
            {"field": "loudness"},
            {"field": "tempo"},
            {"field": "tempo_confidence"},
            {"field": "key"},
            {"field": "key_confidence"},
            {"field": "mode"},
            {"field": "mode_confidence"},
            {"field": "time_signature"},
            {"field": "time_signature_confidence"},
        ),
    },
    {
        "name": "Segment",
        "properties": (
            {"field": "start"},
            {"field": "duration"},
            {"field": "confidence"},
            {"field": "loudness_start"},
            {"field": "loudness_max"},
            {"field": "loudness_max_time"},
            {"field": "loudness_end"},
            {"field": "pitches", "kind": "tuple"},
            {"field": "timbre", "kind": "tuple"},
        ),
    },
    {
        "name": "AudioFeatures",
        "properties": (
            {"field": "acousticness"},
            {"field": "analysis_url"},
            {"field": "danceability"},
            {"field": "duration_ms"},
            {"field": "energy"},
            {"field": "id"},
            {"field": "instrumentalness"},
            {"field": "key"},
            {"field": "liveness"},
            {"field": "loudness"},
            {"field": "mode"},
            {"field": "speechiness"},
            {"field": "tempo"},
            {"field": "time_signature"},
            {"field": "track_href"},
            {"field": "type"},
            {"field": "uri"},
            {"field": "valence"},
        ),
    },
    {
        "name": "AudioAnalysis",
        "properties": (
            {"field": "meta"},
            {"field": "track"},
            {"field": "bars", "kind": "objects", "class": "TimeInterval"},
            {"field": "beats", "kind": "objects", "class": "TimeInterval"},
            {"field": "sections", "kind": "objects", "class": "Section"},
            {"field": "segments", "kind": "objects", "class": "Segment"},
            {"field": "tatums", "kind": "objects", "class": "TimeInterval"},
        ),
    },
    {
        "name": "RecommendationSeed",
        "properties": (
            {"field": "afterFilteringSize"},
            {"field": "afterRelinkingSize"},
            {"field": "href"},
            {"field": "id"},
            {"field": "initialPoolSize"},
            {"field": "type"},
        ),
    },
    {
        "name": "Recommendations",
        "properties": (
            {"field": "seeds", "kind": "objects", "class": "RecommendationSeed"},
            {"field": "tracks", "kind": "objects", "class": "Track"},
        ),
    },
    {
        "name": "Queue",
        "properties": (
            {
                "field": "currently_playing",
                "kind": "typed_object",
                "type_map": {
                    "track": "Track",
                    "episode": "Episode",
                },
            },
            {
                "field": "queue",
                "kind": "typed_objects",
                "type_map": {
                    "track": "Track",
                    "episode": "Episode",
                },
            },
        ),
    },
    {
        "name": "CurrentlyPlaying",
        "properties": (
            {"field": "device", "kind": "object", "class": "Device"},
            {"field": "repeat_state"},
            {"field": "shuffle_state"},
            {"field": "context", "kind": "object", "class": "Context"},
            {"field": "timestamp"},
            {"field": "progress_ms"},
            {"field": "is_playing"},
            {
                "field": "item",
                "kind": "typed_object",
                "type_map": {
                    "track": "Track",
                    "episode": "Episode",
                },
            },
            {"field": "currently_playing_type"},
            {"field": "actions", "kind": "object", "class": "Disallows"},
        ),
    },
    {
        "name": "Artist",
        "fetch_method": "artist",
        "properties": (
            {"field": "id"},
            {"field": "name"},
            {"field": "uri"},
            {"field": "href"},
            {"field": "type"},
            {"field": "external_urls", "kind": "object", "class": "ExternalUrl"},
            {"field": "followers", "kind": "object", "class": "Followers"},
            {"field": "genres", "kind": "tuple"},
            {"field": "images", "kind": "objects", "class": "Image"},
            {"field": "popularity"},
            {
                "field": "albums",
                "kind": "object_by_key",
                "key": "items",
                "present_class": "AlbumPage",
                "absent_class": "AlbumsRef",
                "page_method": "artist_albums",
            },
        ),
    },
    {
        "name": "Album",
        "fetch_method": "album",
        "properties": (
            {"field": "album_type"},
            {"field": "total_tracks"},
            {"field": "available_markets", "kind": "tuple"},
            {"field": "id"},
            {"field": "name"},
            {"field": "uri"},
            {"field": "href"},
            {"field": "type"},
            {"field": "external_urls", "kind": "object", "class": "ExternalUrl"},
            {"field": "images", "kind": "objects", "class": "Image"},
            {"field": "restrictions", "kind": "object", "class": "Restriction"},
            {"field": "release_date"},
            {"field": "release_date_precision"},
            {"field": "artists", "kind": "objects", "class": "Artist"},
            {"field": "copyrights", "kind": "objects", "class": "Copyright"},
            {"field": "external_ids", "kind": "object", "class": "ExternalId"},
            {"field": "genres", "kind": "tuple"},
            {"field": "label"},
            {"field": "popularity"},
            {"field": "tracks", "kind": "object", "class": "TrackPage"},
        ),
    },
    {
        "name": "Track",
        "fetch_method": "track",
        "properties": (
            {"field": "id"},
            {"field": "name"},
            {"field": "uri"},
            {"field": "href"},
            {"field": "type"},
            {"field": "duration_ms"},
            {"field": "explicit"},
            {"field": "disc_number"},
            {"field": "track_number"},
            {"field": "preview_url"},
            {"field": "is_local"},
            {"field": "is_playable"},
            {"field": "available_markets", "kind": "tuple"},
            {"field": "external_urls", "kind": "object", "class": "ExternalUrl"},
            {"field": "linked_from", "kind": "object", "class": "LinkedTrack"},
            {"field": "restrictions", "kind": "object", "class": "Restriction"},
            {"field": "artists", "kind": "objects", "class": "Artist"},
            {"field": "album", "kind": "object", "class": "Album"},
            {"field": "external_ids", "kind": "object", "class": "ExternalId"},
            {"field": "popularity"},
        ),
    },
    {
        "name": "Episode",
        "fetch_method": "episode",
        "properties": (
            {"field": "audio_preview_url"},
            {"field": "description"},
            {"field": "html_description"},
            {"field": "duration_ms"},
            {"field": "explicit"},
            {"field": "id"},
            {"field": "name"},
            {"field": "uri"},
            {"field": "href"},
            {"field": "type"},
            {"field": "external_urls", "kind": "object", "class": "ExternalUrl"},
            {"field": "images", "kind": "objects", "class": "Image"},
            {"field": "is_externally_hosted"},
            {"field": "is_playable"},
            {"field": "language"},
            {"field": "languages", "kind": "tuple"},
            {"field": "release_date"},
            {"field": "release_date_precision"},
            {"field": "resume_point", "kind": "object", "class": "ResumePoint"},
            {"field": "restrictions", "kind": "object", "class": "Restriction"},
            {"field": "show", "kind": "object", "class": "Show"},
        ),
    },
    {
        "name": "Show",
        "fetch_method": "show",
        "properties": (
            {"field": "available_markets", "kind": "tuple"},
            {"field": "description"},
            {"field": "html_description"},
            {"field": "explicit"},
            {"field": "href"},
            {"field": "id"},
            {"field": "is_externally_hosted"},
            {"field": "languages", "kind": "tuple"},
            {"field": "media_type"},
            {"field": "name"},
            {"field": "publisher"},
            {"field": "type"},
            {"field": "uri"},
            {"field": "total_episodes"},
            {"field": "copyrights", "kind": "objects", "class": "Copyright"},
            {"field": "external_urls", "kind": "object", "class": "ExternalUrl"},
            {"field": "images", "kind": "objects", "class": "Image"},
            {"field": "episodes", "kind": "object", "class": "EpisodePage"},
        ),
    },
    {
        "name": "SavedAlbum",
        "properties": (
            {"field": "added_at"},
            {"field": "album", "kind": "object", "class": "Album"},
        ),
    },
    {
        "name": "SavedTrack",
        "properties": (
            {"field": "added_at"},
            {"field": "track", "kind": "object", "class": "Track"},
        ),
    },
    {
        "name": "SavedEpisode",
        "properties": (
            {"field": "added_at"},
            {"field": "episode", "kind": "object", "class": "Episode"},
        ),
    },
    {
        "name": "SavedShow",
        "properties": (
            {"field": "added_at"},
            {"field": "show", "kind": "object", "class": "Show"},
        ),
    },
    {
        "name": "PlayHistory",
        "properties": (
            {"field": "track", "kind": "object", "class": "Track"},
            {"field": "played_at"},
            {"field": "context", "kind": "object", "class": "Context"},
        ),
    },
    {
        "name": "Audiobook",
        "fetch_method": "audiobook",
        "properties": (
            {"field": "authors", "kind": "objects", "class": "Author"},
            {"field": "available_markets", "kind": "tuple"},
            {"field": "copyrights", "kind": "objects", "class": "Copyright"},
            {"field": "description"},
            {"field": "html_description"},
            {"field": "edition"},
            {"field": "explicit"},
            {"field": "href"},
            {"field": "id"},
            {"field": "images", "kind": "objects", "class": "Image"},
            {"field": "languages", "kind": "tuple"},
            {"field": "media_type"},
            {"field": "name"},
            {"field": "narrators", "kind": "objects", "class": "Narrator"},
            {"field": "publisher"},
            {"field": "type"},
            {"field": "uri"},
            {"field": "total_chapters"},
            {"field": "external_urls", "kind": "object", "class": "ExternalUrl"},
            {"field": "chapters", "kind": "object", "class": "ChapterPage"},
        ),
    },
    {
        "name": "Chapter",
        "fetch_method": "chapter",
        "properties": (
            {"field": "audio_preview_url"},
            {"field": "available_markets", "kind": "tuple"},
            {"field": "chapter_number"},
            {"field": "description"},
            {"field": "html_description"},
            {"field": "duration_ms"},
            {"field": "explicit"},
            {"field": "href"},
            {"field": "id"},
            {"field": "images", "kind": "objects", "class": "Image"},
            {"field": "is_playable"},
            {"field": "languages", "kind": "tuple"},
            {"field": "name"},
            {"field": "release_date"},
            {"field": "release_date_precision"},
            {"field": "type"},
            {"field": "uri"},
            {"field": "external_urls", "kind": "object", "class": "ExternalUrl"},
            {"field": "resume_point", "kind": "object", "class": "ResumePoint"},
            {"field": "restrictions", "kind": "object", "class": "Restriction"},
            {"field": "audiobook", "kind": "object", "class": "Audiobook"},
        ),
    },
    {
        "name": "PlaylistTrack",
        "properties": (
            {"field": "added_at"},
            {"field": "added_by", "kind": "object", "class": "User"},
            {"field": "is_local"},
            {
                "field": "item",
                "kind": "typed_object",
                "type_map": {
                    "track": "Track",
                    "episode": "Episode",
                },
            },
        ),
    },
    {
        "name": "Playlist",
        "fetch_method": "playlist",
        "properties": (
            {"field": "collaborative"},
            {"field": "description"},
            {"field": "href"},
            {"field": "id"},
            {"field": "name"},
            {"field": "public"},
            {"field": "snapshot_id"},
            {"field": "type"},
            {"field": "uri"},
            {"field": "external_urls", "kind": "object", "class": "ExternalUrl"},
            {"field": "images", "kind": "objects", "class": "Image"},
            {"field": "owner", "kind": "object", "class": "User"},
            {
                "field": "items",
                "kind": "object_by_key",
                "key": "items",
                "present_class": "PlaylistTrackPage",
                "absent_class": "PlaylistItemsRef",
                "page_method": "playlist_items",
            },
        ),
    },
)
