from .object_specs import SPOTIFY_OBJECT_SPECS


OPENAPI_SCHEMA_NAMES = (
    "LinkedTrackObject",
    "TrackRestrictionObject",
    "AlbumRestrictionObject",
    "EpisodeRestrictionObject",
    "ChapterRestrictionObject",
    "ArtistObject",
    "SimplifiedArtistObject",
    "PlayHistoryObject",
    "PlaylistTrackObject",
    "QueueObject",
    "CurrentlyPlayingContextObject",
    "DisallowsObject",
    "ErrorObject",
    "PrivateUserObject",
    "PublicUserObject",
    "AudioAnalysisObject",
    "TimeIntervalObject",
    "SectionObject",
    "SegmentObject",
    "TimeSignature",
    "Tempo",
    "Loudness",
    "Key",
    "Mode",
    "AudioFeaturesObject",
    "SimplifiedTrackObject",
    "DeviceObject",
    "CursorObject",
    "CursorPagingObject",
    "CursorPagingPlayHistoryObject",
    "CursorPagingSimplifiedArtistObject",
    "PagingObject",
    "PagingPlaylistObject",
    "PagingFeaturedPlaylistObject",
    "PagingArtistDiscographyAlbumObject",
    "PagingSimplifiedAlbumObject",
    "PagingSavedAlbumObject",
    "PagingSimplifiedTrackObject",
    "PagingSavedTrackObject",
    "PagingTrackObject",
    "PagingPlaylistTrackObject",
    "PagingSimplifiedShowObject",
    "PagingSavedShowObject",
    "PagingSimplifiedEpisodeObject",
    "PagingSavedEpisodeObject",
    "PagingSimplifiedAudiobookObject",
    "PagingArtistObject",
    "PagingSimplifiedChapterObject",
    "RecommendationsObject",
    "RecommendationSeedObject",
    "SavedAlbumObject",
    "SavedTrackObject",
    "SavedEpisodeObject",
    "SavedShowObject",
    "PlaylistObject",
    "SimplifiedPlaylistObject",
    "PlaylistItemsRefObject",
    "PlaylistUserObject",
    "PlaylistOwnerObject",
    "CategoryObject",
    "TrackObject",
    "EpisodeObject",
    "SimplifiedEpisodeObject",
    "EpisodeBase",
    "ResumePointObject",
    "ShowBase",
    "ShowObject",
    "SimplifiedShowObject",
    "AudiobookBase",
    "AudiobookObject",
    "SimplifiedAudiobookObject",
    "AlbumBase",
    "SimplifiedAlbumObject",
    "ArtistDiscographyAlbumObject",
    "ChapterObject",
    "SimplifiedChapterObject",
    "ChapterBase",
    "AlbumObject",
    "ContextObject",
    "CopyrightObject",
    "AuthorObject",
    "NarratorObject",
    "ExternalIdObject",
    "ExternalUrlObject",
    "FollowersObject",
    "ImageObject",
    "ExplicitContentSettingsObject",
)


SCHEMA_TO_SPEC = {
    "AlbumBase": "Album",
    "AlbumObject": "Album",
    "AlbumRestrictionObject": "Restriction",
    "ArtistDiscographyAlbumObject": "Album",
    "ArtistObject": "Artist",
    "AudioAnalysisObject": "AudioAnalysis",
    "AudioFeaturesObject": "AudioFeatures",
    "AuthorObject": "Author",
    "AudiobookBase": "Audiobook",
    "AudiobookObject": "Audiobook",
    "CategoryObject": "Category",
    "ChapterBase": "Chapter",
    "ChapterObject": "Chapter",
    "ChapterRestrictionObject": "Restriction",
    "ContextObject": "Context",
    "CopyrightObject": "Copyright",
    "CursorObject": "Cursor",
    "CurrentlyPlayingContextObject": "CurrentlyPlaying",
    "DeviceObject": "Device",
    "DisallowsObject": "Disallows",
    "ErrorObject": "Error",
    "CursorPagingObject": "CursorPage",
    "CursorPagingPlayHistoryObject": "PlayHistoryCursorPage",
    "CursorPagingSimplifiedArtistObject": "ArtistCursorPage",
    "EpisodeBase": "Episode",
    "EpisodeObject": "Episode",
    "EpisodeRestrictionObject": "Restriction",
    "ExplicitContentSettingsObject": "ExplicitContentSettings",
    "ExternalIdObject": "ExternalId",
    "ExternalUrlObject": "ExternalUrl",
    "FollowersObject": "Followers",
    "ImageObject": "Image",
    "LinkedTrackObject": "LinkedTrack",
    "NarratorObject": "Narrator",
    "PagingArtistDiscographyAlbumObject": "AlbumPage",
    "PagingArtistObject": "ArtistPage",
    "PagingFeaturedPlaylistObject": "FeaturedPlaylists",
    "PagingObject": "Paging",
    "PagingPlaylistObject": "PlaylistPage",
    "PagingPlaylistTrackObject": "PlaylistTrackPage",
    "PagingSavedAlbumObject": "SavedAlbumPage",
    "PagingSavedEpisodeObject": "SavedEpisodePage",
    "PagingSavedShowObject": "SavedShowPage",
    "PagingSavedTrackObject": "SavedTrackPage",
    "PagingSimplifiedAlbumObject": "AlbumPage",
    "PagingSimplifiedAudiobookObject": "AudiobookPage",
    "PagingSimplifiedChapterObject": "ChapterPage",
    "PagingSimplifiedEpisodeObject": "EpisodePage",
    "PagingSimplifiedShowObject": "ShowPage",
    "PagingSimplifiedTrackObject": "TrackPage",
    "PagingTrackObject": "TrackPage",
    "PlayHistoryObject": "PlayHistory",
    "PlaylistObject": "Playlist",
    "PlaylistTrackObject": "PlaylistTrack",
    "PlaylistOwnerObject": "User",
    "PlaylistItemsRefObject": "PlaylistItemsRef",
    "PlaylistUserObject": "User",
    "PrivateUserObject": "PrivateUser",
    "PublicUserObject": "User",
    "QueueObject": "Queue",
    "RecommendationSeedObject": "RecommendationSeed",
    "RecommendationsObject": "Recommendations",
    "ResumePointObject": "ResumePoint",
    "SavedAlbumObject": "SavedAlbum",
    "SavedEpisodeObject": "SavedEpisode",
    "SavedShowObject": "SavedShow",
    "SavedTrackObject": "SavedTrack",
    "SectionObject": "Section",
    "SegmentObject": "Segment",
    "ShowBase": "Show",
    "ShowObject": "Show",
    "SimplifiedAlbumObject": "Album",
    "SimplifiedArtistObject": "Artist",
    "SimplifiedAudiobookObject": "Audiobook",
    "SimplifiedChapterObject": "Chapter",
    "SimplifiedEpisodeObject": "Episode",
    "SimplifiedPlaylistObject": "Playlist",
    "SimplifiedShowObject": "Show",
    "SimplifiedTrackObject": "Track",
    "TimeIntervalObject": "TimeInterval",
    "TrackObject": "Track",
    "TrackRestrictionObject": "Restriction",
}


SKIPPED_SCHEMA_NAMES = (
    "Key",
    "Loudness",
    "Mode",
    "Tempo",
    "TimeSignature",
)


def spec_names():
    return tuple(spec["name"] for spec in SPOTIFY_OBJECT_SPECS)


def uncovered_schema_names():
    specs = set(spec_names())
    skipped = set(SKIPPED_SCHEMA_NAMES)
    missing = []

    for schema_name in OPENAPI_SCHEMA_NAMES:
        mapped = SCHEMA_TO_SPEC.get(schema_name)
        if schema_name in skipped:
            continue
        if mapped not in specs:
            missing.append(schema_name)

    return tuple(missing)
